apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3-exporter.fullname" . }}
  labels:
    {{- include "s3-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "s3-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "s3-exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "s3-exporter.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: GLOBAL_BUCKET
              value: {{ .Values.global.bucket }}
            - name: GLOBAL_PREFIX
              value: {{ .Values.global.prefix | default "" }}
            - name: GLOBAL_S3_ENDPOINT_URL
              value: {{ .Values.global.s3.endpoint_url }}
            - name: GLOBAL_S3_REGION
              value: {{ .Values.global.s3.region | default "us-east-1" }}
            - name: GLOBAL_SECRET_KEYS_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.global.existingSecret }}
                  key: {{ .Values.global.secretKeys.access_key }}
            - name: GLOBAL_SECRET_KEYS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.existingSecret }}
                  key: {{ .Values.global.secretKeys.secret_key }}
            - name: EXPORTER_PORT
              value: "{{ .Values.exporter.port }}"
            - name: EXPORTER_CHECK_INTERVAL_SECONDS
              value: "{{ .Values.exporter.checkIntervalSeconds }}"

            {{- range $i, $f := .Values.files }}
            - name: FILE_{{ $i }}_KEY
              value: {{ $f.key | quote }}
            {{- if $f.bucket }}
            - name: FILE_{{ $i }}_BUCKET
              value: {{ $f.bucket | quote }}
            {{- end }}
            {{- end }}

          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
