name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 's3_exporter.py'
      - 'Dockerfile'
      - '.github/workflows/**'
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get date-based version tag
      id: version
      run: echo "tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/custom-s3-exporter:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/custom-s3-exporter:${{ steps.version.outputs.tag }}